[package]
name = "rfdns"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["cors"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json"] }
hickory-proto = "0.24"
hickory-client = "0.24"
hickory-resolver = "0.24"
base64 = "0.21"
ipnet = "2.8"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
moka = { version = "0.12", features = ["sync"] }
once_cell = "1.19"
tokio-rustls = "0.25"
rustls = "0.23"
rustls-pemfile = "2.1"
rcgen = "0.13"
clap = { version = "4.0", features = ["derive"] }
rand = "0.8"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
