[build]
jobs = 8

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld", "-C", "target-cpu=native"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
rustflags = ["-C", "link-arg=-fuse-ld=lld", "-C", "target-cpu=native"]

[profile.dev]
opt-level = 1
debug = true
split-debuginfo = "unpacked"
incremental = true

[cargo-new]
name = "rfdns"
email = "me@nergis.dev"

[registries.crates-io]
protocol = "sparse"

[env]
CARGO_TARGET_DIR = "target"
